services:
  web:
    build: .
    container_name: sepwebdev-web-1
    volumes:
      - ../showmetheworld/dist:/var/www/html/public/showmetheworld
      - ../showmetheworld/smtw-backend:/var/www/html/public/smtw-backend
      - ./public/store/images/uploaded:/var/www/html/public/store/images/uploaded
    environment:
      - DB_HOST=sep-common-db-1
      - DB_CONNECTION=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-sepwebdev}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - npm_default
      - sep_common_net

networks:
  npm_default:
    external: true
  sep_common_net:
    external: true
